name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.27
        env:
          MYSQL_DATABASE: testdb
          MYSQL_ROOT_PASSWORD: rootpass
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Using Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4.0.1
        with:
          node-version: ${{matrix.node-version}}
      - name: Start Mysql Service
        run: sudo /etc/init.d/mysql start
      - name: Install npm dependencies
        run: npm ci
      - name: Transfer .env.test file
        run: |
          echo "DATABASE_TYPE=mysql" >> .env.test
          echo "DATABASE_PORT=3306" >> .env.test
          echo "DATABASE_HOST=127.0.0.1" >> .env.test
          echo "DATABASE_USERNAME=root" >> .env.test
          echo "DATABASE_PASSWORD=rootpass" >> .env.test
          echo "DATABASE_DATABASE=testdb" >> .env.test
          echo "JWT_SECRET=se" >> .env.test
      - name: Connect To Mysql
        run: mysql -h 127.0.0.1 --port 3306 -u root -prootpass
      - name: Run the test
        run: npm run test
        
      